name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests

      - name: Download dataset
        run: python src/get_data.py

      - name: Sanity check data exists
        run: |
          ls -la "data/raw" || true
          ls -la "data/raw/UCI HAR Dataset" || true
          test -f "data/raw/UCI HAR Dataset/train/X_train.txt"

      - name: Run tests
        run: pytest -q --maxfail=1



